### ISSUE TITLE
Support PHP 8.0 and Dahsboard version 2

### ISSUE THREAD

**Issue by sitenzo** [solitweb/laravel-dashboard-weather-forecast-tile#1]
Hello Solitweb. 

Is it possible to support Dashboard V2.0 and PHP version 8.0?
I get following error.

`
   [InvalidArgumentException]
     Package solitweb/laravel-dashboard-weather-forecast-tile has a PHP requirement incompatible with your PHP version, PHP 
   extensions and Composer version:
    - solitweb/laravel-dashboard-weather-forecast-tile requires php ^7.4 which does not match your installed version 8.0.0.
    - solitweb/laravel-dashboard-weather-forecast-tile requires spatie/laravel-dashboard ^2.0 but it is not present.`

Thanks

**Comment by stijnvanouplines** [comment]
Check new release v1.0.1
